Repository spicecodecli/spicecode, pull requests merged in 2025-04, with the labels that each got.

#128 Add export command and results exporting functionality
  CODE_OF_CONDUCT.md
  cli/commands/analyze.py
  cli/commands/export/__init__.py
  cli/commands/export/export.py
  cli/main.py
  lexers/golang/golexer.py
  lexers/javascript/javascriptlexer.py
  spice/analyze.py
Labels: documentation

#131 Structural changes
  cli/commands/analyze.py
  cli/commands/export/export.py
  cli/commands/hello.py
  cli/commands/version.py
  spice/analyze.py
  spice/utils/__init__.py
  utils/__init__.py
  utils/get_lang.py
  utils/get_lexer.py
  utils/get_translation.py
Labels: enhancement

#135 Fix everything
  spice/analyze.py
  spice/analyzers/count_comment_lines.py
  spice/analyzers/count_functions.py
  spice/analyzers/count_lines.py
  tests/analyze/test_analyze_json_go.py
  tests/analyze/test_analyze_json_javascript.py
  tests/analyze/test_analyze_json_ruby.py
Labels: bug, enhancement
