Repository spicecodecli/spicecode, pull requests merged in 2025-05, with the labels that each got.

#142 improve README formatting and clarity
  README.md
Labels: documentation

#149 N2 gustavo
  cli/commands/analyze.py
  cli/translations/en.py
  cli/translations/fremen.py
  cli/translations/pt-br.py
  spice/analyze.py
  spice/analyzers/count_comment_ratio.py
  temp_test.js
  temp_test.py
  tests/analyze/test_analyze_comment_ratio.py
  tests/analyze/test_analyze_method_type.py
Labels: enhancement

#151 new README updated for version 2.0
  README.md
Labels: documentation, enhancement

#153 Pipy publishing workflow
  .github/workflows/publishing.yml
  setup.py
Labels: enhancement

#155 Publishing workflow fixes
  .github/workflows/publishing.yml
  setup.py
Labels: bug

#159 update pypi info
  setup.py
Labels: documentation

#161 license fix
  setup.py
Labels: bug, documentation

#170 remove cache from docusaurus gh pages workflow
  .github/workflows/deploy.yml
Labels: bug

#174 fix base url
  docs/docusaurus.config.js
Labels: bug, documentation, enhancement

#175 Docs improvements
  docs/docusaurus.config.js
  docs/src/css/custom.css
  docs/src/pages/index.js
Labels: documentation, enhancement

#176 create .gitattributes
  .gitattributes
Labels: documentation, enhancement

#177 cleaning the repo
  temp_test.js
  temp_test.py
Labels: enhancement

#178 More temp files to clean i cant believe this
  tests/temp_test.js
  tests/temp_test.py
Labels: enhancement

#179 New tests 2
  .github/workflows/run_tests.yml
  tests/cli/__init__.py
  tests/cli/commands/__init__.py
  tests/cli/commands/test_version.py
  tests/lexers/__init__.py
  tests/lexers/test_golexer.py
  tests/lexers/test_javascriptlexer.py
  tests/lexers/test_pythonlexer.py
  tests/lexers/test_rubylexer.py
  tests/lexers/test_token.py
  tests/parser/__init__.py
  tests/parser/test_ast.py
  tests/sample-code/func_sample.go
  tests/sample-code/func_sample.js
  tests/sample-code/func_sample.py
  tests/sample-code/func_sample.rb
  tests/sample-code/ratio_sample.go
  tests/sample-code/ratio_sample.js
  tests/sample-code/ratio_sample.py
  tests/sample-code/ratio_sample.rb
  tests/sample-code/sample_comments.py
  tests/spice/__init__.py
  tests/spice/analyzers/__init__.py
  tests/spice/analyzers/test_count_comment_lines.py
  tests/spice/analyzers/test_count_comment_ratio.py
  tests/spice/analyzers/test_count_functions.py
  tests/spice/analyzers/test_count_inline_comments.py
  tests/spice/analyzers/test_count_lines.py
  tests/utils/__init__.py
  tests/utils/test_get_lang.py
  tests/utils/test_get_lexer.py
  tests/utils/test_get_translation.py
Labels: enhancement, help wanted, tests

#182 update readme title and slogan
  README.md
Labels: documentation, enhancement

#184 gitignore docusaurus cache
  docs/.gitignore
Labels: enhancement

#185 test workflow will generate XML coverage report
  .github/workflows/run_tests.yml
Labels: enhancement, tests

#186 Run sonarqube with gh workflow
  .github/workflows/run_tests.yml
  sonar-project.properties
Labels: enhancement, tests

#189 add pypi link to the top of readme
  README.md
Labels: documentation, enhancement

#190 add docs website to readme
  README.md
Labels: documentation, enhancement
