Repository spicecodecli/spicecode, pull requests merged in 2025-03, with the labels that each got.

#13 feat: adiciona PythonAnalyzer para análise de arquivos Python
  lexers/python/__init__.py
  lexers/python/pythonlexer.py
  lexers/ruby/rubylexer.py
  lexers/token.py
  parser/parser.py
  spice/analyze.py
Labels: enhancement

#20 main branch protection test
  README.md
Labels: enhancement

#21 Separate sample code into own folder
  sample-code/example.py
  sample-code/example.rb
Labels: enhancement

#25 feat: add GoAnalyzer and lexer for Go file analysis
  lexers/golang/__init__.py
  lexers/golang/golexer.py
  spice/analyze.py
Labels: enhancement

#50 update readme to include new translate command
  README.md
Labels: documentation, enhancement

#79 add: complex code examples in JavaScript and Python
  sample-code/example.js
  sample-code/example.py
  sample-code/exemple.go
Labels: TODO

#92 Create codeql.yml
  .github/workflows/codeql.yml
Labels: enhancement

#93 Create FUNDING.yml
  .github/FUNDING.yml
Labels: enhancement

#94 Create SECURITY.md
  SECURITY.md
Labels: documentation, enhancement

#95 Update SECURITY.md
  SECURITY.md
Labels: documentation, enhancement

#105 Fix tests
  cli/main.py
  requirements.txt
  spice/analyze.py
  tests/analyze/test_analyze_json_python-example.py
  tests/sample-code/example.go
  tests/sample-code/example.js
  tests/sample-code/example.py
  tests/sample-code/example.rb
  tests/unit/__init__.py
  tests/unit/test_analyze.py
Labels: bug

#113 aweasdads
  cli/main.py
  spice/analyze.py
  spice/identation.py
Labels: help wanted, question

#116 remove unused imports
  cli/main.py
Labels: enhancement

#118 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#119 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#120 make code of conduct dune themed
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement

#123 remove unused import
  tests/analyze/test_analyze_json_python-example.py
Labels: enhancement
